server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #          uri: file://${HOME}/config-repo
          #          uri: https://github.com/ericdahl/spring-cloud-config-example
          uri: https://github.com/Vishalsvisual/demo-external-config/

          # Search in the 'server-config' directory of the repo. This generally wouldn't
          # be used because the configs would be in the root directory, but because
          # this example repo is hosting both the code and the configs, we're
          # isolating the configuration files into their own directory.
          search-paths:
            - server-config
          #searchPaths: server-config

# enable all actuator endpoints for testing (review this for real deployments)
#management.endpoints.web:
#  include: '*'